### ISSUE TITLE
Cannot drag or crop the image.

### ISSUE THREAD

**Issue by muneeb2542** [CampusLabs/imgareaselect-rails#2]
I have used this plugin on my application.It works absolutely fine when use my application locally but when i use it from the deployed version on live,the drag and crop options both do not work.

**Comment by AaronLasseigne** [comment]
This gem just makes the imgAreaSelect assets (i.e. JS, CSS, images) available in Rails. Any issues with the underlying code need to be reported to the original author. Unfortunately, I believe the package has been abandoned. There haven't been changes in a long time.

**Comment by tfausak** [comment]
Yup. Your best bet is to open an issue against https://github.com/odyniec/imgareaselect.
